## Phase 1: ML Foundation (Day 1–20)
# DAY 10 — FULL ML PIPELINE (BIG DAY)

### Now we combine everything you learned 

**🧠 Goal**

* You will build:
   - End-to-End ML Project

## YOUR TASK (STEP BY STEP)

🛠️ Dataset (I give you ready — no need to create)
data = {
    "Hours": [1,2,3,4,5,6,7,8],
    "Practice": [10,20,30,40,50,60,70,80],
    "Gender": ["Male","Female","Female","Male","Male","Female","Male","Female"],
    "Marks": [12,22,32,42,52,62,72,82]
}
🎯 YOUR TASK (STEP BY STEP)
✅ Step 1: Create DataFrame
✅ Step 2: Handle Encoding
👉 Convert Gender → numeric (One-Hot)

✅ Step 3: Define X and y
X → all input columns  
y → Marks

✅ Step 4: Train Model
Use:
LinearRegression

✅ Step 5: Prediction
Predict for:

Hours = 9  
Practice = 90  
Gender = Male

⚠️ Important Reminder
👉 You must:

Encode input also (Gender_Male / Gender_Female)
🧠 Final Question
After doing full pipeline, answer:

What are the 5 steps of ML pipeline you just performed?

In [33]:
# ✅ Step 1: Create DataFrame

data = {
    "Hours": [1,2,3,4,5,6,7,8],
    "Practice": [10,20,30,40,50,60,70,80],
    "Gender": ["Male","Female","Female","Male","Male","Female","Male","Female"],
    "Marks": [12,22,32,42,52,62,72,82]
}
import pandas as pd

df = pd.DataFrame(data)
df

   Hours  Practice  Gender  Marks
0      1        10    Male     12
1      2        20  Female     22
2      3        30  Female     32
3      4        40    Male     42
4      5        50    Male     52
5      6        60  Female     62
6      7        70    Male     72
7      8        80  Female     82

In [34]:
# ✅ Step 2: Handle Encoding
# 👉 Convert Gender → numeric (One-Hot)

encoded_df = pd.get_dummies(df, columns = ['Gender'], dtype = 'int')
encoded_df

   Hours  Practice  Marks  Gender_Female  Gender_Male
0      1        10     12              0            1
1      2        20     22              1            0
2      3        30     32              1            0
3      4        40     42              0            1
4      5        50     52              0            1
5      6        60     62              1            0
6      7        70     72              0            1
7      8        80     82              1            0

In [35]:
# ✅ Step 3: Define X and y
# X → all input columns  
# y → Marks

X = encoded_df.drop(columns = 'Marks')
y = encoded_df['Marks']

In [36]:
# ✅ Step 4: Train Model
# Use:
# LinearRegression

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [37]:
# ✅ Step 5: Prediction
# Predict for:

# Hours = 9  
# Practice = 90  
# Gender = Male


new_data = pd.DataFrame({'Hours':[9], 'Practice':[90], 'Gender_Female':[0], 'Gender_Male':[1]})
model.predict(new_data)

array([92.])

## One Important Habit (From Now On)
### Whenever you build any ML model, always think:

1. Data ready?  
2. Cleaned?  
3. Encoded?  
4. Features defined?  
5. Model trained?  
6. Prediction format correct?
### 👉 This checklist will save you from 90% of mistakes