## Phase 1: ML Foundation (Day 1–20)
#  DAY 8 — Encoding (Categorical Data)

## 🧠 Concept

Till now:

👉 All data was numeric

### But real-world:

* Gender → Male/Female
* Department → HR/IT/Sales
* 
## 👉 Models cannot understand text

### 🤔 THINK FIRST

**Answer this:**

1. Why can’t ML models use text directly?
2. What can we convert text into so model can understand?

In [ ]:
# ML models cannot understand text directly because they work on mathematical calculations, which require numerical input.

# We convert text into numerical format so the model can process it.

# Encoding Types
### Now we learn how to convert text → numbers.

## 🧠 Two Main Methods
# 🔹 1. Label Encoding

Example:

**Gender:**

* Male → 0
* Female → 1


* 👉 Simple conversion
* 👉 But model may think:

### 1 > 0 (which is not true meaning-wise)


# 🔹 2. One-Hot Encoding (Better)

Example:

**Gender:**

* Male   → [1, 0]
* Female → [0, 1]

* 👉 No ranking problem ✔️
* 👉 Preferred in most cases ✔️

## 🤔 THINK
### Answer this:

1. Which is better for categories like "Red, Blue, Green"?
  *  Label Encoding OR One-Hot Encoding?

2. Why is Label Encoding risky sometimes?

In [ ]:
# ✅ 1. Which is better for "Red, Blue, Green"?
# 👉 One-Hot Encoding ✔️

# ✅ 2. Why is Label Encoding risky?
# 👉 Because it introduces a false order/ranking between categories, which can mislead the model.

## ✅ 1. Which is better for "Red, Blue, Green"?
### 👉 One-Hot Encoding ✔️

🧠 Why?

Because:

* Red ≠ Blue ≠ Green (no order, no ranking)
  
* If you use Label Encoding:

* Red → 0
* Blue → 1
* Green → 2

* 
❌ Model may think:

Green > Blue > Red (WRONG meaning)


## ✅ 2. Why is Label Encoding risky?

👉 Correct answer:

### Because it introduces a false order/ranking between categories, which can mislead the model.

## 🔥 Simple Rule (Remember This)

## No order in categories → One-Hot Encoding ✅  
## Order exists (Low, Medium, High) → Label Encoding ✅

#  Coding Task (Encoding)

In [7]:
# Dataset
data = {
    "Hours": [1, 2, 3, 4],
    "Gender": ["Male", "Female", "Female", "Male"],
    "Marks": [10, 20, 30, 40]
}
import pandas as pd
df = pd.DataFrame(data)
df

   Hours  Gender  Marks
0      1    Male     10
1      2  Female     20
2      3  Female     30
3      4    Male     40

## Task : 1
#### 👉 Do One-Hot Encoding:

In [20]:
# df_encoded = pd.get_dummies(df, columns = df['Gender'])     # It's the minor mistake that you should care of that.
df_encoded = pd.get_dummies(df, columns=["Gender"])
df_encoded

   Hours  Marks  Gender_Female  Gender_Male
0      1     10          False         True
1      2     20           True        False
2      3     30           True        False
3      4     40          False         True

## dtype = 'int'
#### From True / False to 0 / 1 conversion

In [41]:
df_encoded = pd.get_dummies(df, columns=["Gender"], dtype = 'int')
df_encoded

   Hours  Marks  Gender_Female  Gender_Male
0      1     10              0            1
1      2     20              1            0
2      3     30              1            0
3      4     40              0            1

## 🧠 Mini Question

#### 👉 After encoding:

**How many new columns are created for Gender?**

**2 New Columns Created:**

* Gender_Female  
* Gender_Male

# Train Model on Encoded Data

🛠️ Your Task
Define:

X = df_encoded.drop("Marks", axis=1)
y = df_encoded["Marks"]
Train model:

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, y)
🎯 Prediction Task
Predict for:

Hours = 5  
Gender = Male
👉 Input should be:

Hours = 5
Gender_Female = 0
Gender_Male = 1
🧠 Mini Question
👉 Why do we need BOTH columns (Gender_Female and Gender_Male)?

(1 line answer)

In [42]:
# Dataset
df

   Hours  Gender  Marks
0      1    Male     10
1      2  Female     20
2      3  Female     30
3      4    Male     40

In [43]:
X = df_encoded.drop('Marks', axis = 1)
y = df_encoded['Marks']

In [44]:
# Train the Model

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [54]:
# Predict for:

# Hours = 5  
# Gender = Male

new_data = pd.DataFrame({'Hours':[5], 'Gender_Female':[1], 'Gender_Male':[0]}) # After the cat coding we will give input in coded format
# new_data
model.predict(new_data)

array([50.])

## Mini Question Answer
#### 👉 Why do we need BOTH columns?

### ✅ Correct Answer:
## Because one-hot encoding represents each category separately, so model can understand them without assuming any order.